<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="SystemControl" Id="{f26ced33-dea7-45dd-a280-164c04479403}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK SystemControl
VAR_IN_OUT
	motor_axis : Tc2_MC2.AXIS_REF;
	system_control_param : SystemControlParam;
	motor_state : MotorState;
END_VAR
VAR_OUTPUT
	target_velocity : LREAL;
END_VAR
VAR
	motorPower : Tc2_MC2.MC_Power;
END_VAR
]]></Declaration>
    <Implementation>
      <StateChart>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="UMLStateChart">
              <v n="Abortable">true</v>
              <v n="UseVarInstForMethods">false</v>
              <v n="StatesCount">16</v>
              <v n="HistoryCount">0</v>
              <v n="TransitionsCount">23</v>
              <v n="RegionsCount">0</v>
              <v n="TracesCount">0</v>
              <v n="StatesInitString">":=[(ID := 1, Name := 'GeneratedStartStateForAbort1', StateType := _UML_SC_StateTypes.InitialState, StartOfTransitionIndex := 1, OutGoingTransitionsCount := 1, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 2, Name := 'GeneratedFinalStateForAbort1', StateType := _UML_SC_StateTypes.FinalState, StartOfTransitionIndex := 0, OutGoingTransitionsCount := 0, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 3, Name := 'EndState1', StateType := _UML_SC_StateTypes.FastState, StartOfTransitionIndex := 2, OutGoingTransitionsCount := 1, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 4, Name := 'ChoiceElement1', StateType := _UML_SC_StateTypes.FastState, StartOfTransitionIndex := 3, OutGoingTransitionsCount := 3, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 0, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 5, Name := 'EndState2', StateType := _UML_SC_StateTypes.FastState, StartOfTransitionIndex := 6, OutGoingTransitionsCount := 1, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 6, Name := 'ConstForceControl', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 7, OutGoingTransitionsCount := 1, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := True, HasExitAction := False) , 
(ID := 7, Name := 'HoldOn', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 8, OutGoingTransitionsCount := 2, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 8, Name := 'StartState2', StateType := _UML_SC_StateTypes.FastState, StartOfTransitionIndex := 10, OutGoingTransitionsCount := 1, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 9, Name := 'DebugReady', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 11, OutGoingTransitionsCount := 2, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := True, HasExitAction := False) , 
(ID := 10, Name := 'SystemExit', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 13, OutGoingTransitionsCount := 1, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := True, HasExitAction := False) , 
(ID := 11, Name := 'DebugJog', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 14, OutGoingTransitionsCount := 1, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := True, HasExitAction := False) , 
(ID := 12, Name := 'StartState3', StateType := _UML_SC_StateTypes.FastState, StartOfTransitionIndex := 15, OutGoingTransitionsCount := 1, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 13, Name := 'ConstForceReady', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 16, OutGoingTransitionsCount := 2, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := True, HasExitAction := False) , 
(ID := 14, Name := 'Ready', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 18, OutGoingTransitionsCount := 3, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := True, HasExitAction := False) , 
(ID := 15, Name := 'PowerOn', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 21, OutGoingTransitionsCount := 2, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := True, HasExitAction := False) , 
(ID := 16, Name := 'StartState1', StateType := _UML_SC_StateTypes.FastState, StartOfTransitionIndex := 23, OutGoingTransitionsCount := 1, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) ];
"</v>
              <v n="TransitionsInitString">":=[(ID := 1, StartStateID := 1, EndStateID := 16, Priority := 1, HasAction := False, IsCompletion := True,IsPseudoException := False,IsException := False), 
(ID := 2, StartStateID := 3, EndStateID := 14, Priority := 1, HasAction := False, IsCompletion := True,IsPseudoException := False,IsException := False), 
(ID := 3, StartStateID := 4, EndStateID := 2, Priority := 1, HasAction := True, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 4, StartStateID := 4, EndStateID := 12, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 5, StartStateID := 4, EndStateID := 8, Priority := 3, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 6, StartStateID := 5, EndStateID := 14, Priority := 1, HasAction := False, IsCompletion := True,IsPseudoException := False,IsException := False), 
(ID := 7, StartStateID := 6, EndStateID := 13, Priority := 1, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 8, StartStateID := 7, EndStateID := 2, Priority := 1, HasAction := True, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 9, StartStateID := 7, EndStateID := 15, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 10, StartStateID := 8, EndStateID := 9, Priority := 1, HasAction := False, IsCompletion := True,IsPseudoException := False,IsException := False), 
(ID := 11, StartStateID := 9, EndStateID := 3, Priority := 1, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 12, StartStateID := 9, EndStateID := 11, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 13, StartStateID := 10, EndStateID := 2, Priority := 1, HasAction := True, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 14, StartStateID := 11, EndStateID := 9, Priority := 1, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 15, StartStateID := 12, EndStateID := 13, Priority := 1, HasAction := False, IsCompletion := True,IsPseudoException := False,IsException := False), 
(ID := 16, StartStateID := 13, EndStateID := 5, Priority := 1, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 17, StartStateID := 13, EndStateID := 6, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 18, StartStateID := 14, EndStateID := 2, Priority := 1, HasAction := True, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 19, StartStateID := 14, EndStateID := 10, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 20, StartStateID := 14, EndStateID := 4, Priority := 3, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 21, StartStateID := 15, EndStateID := 2, Priority := 1, HasAction := True, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 22, StartStateID := 15, EndStateID := 14, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 23, StartStateID := 16, EndStateID := 7, Priority := 1, HasAction := False, IsCompletion := True,IsPseudoException := False,IsException := False)];
"</v>
              <v n="RegionsInitString">""</v>
              <v n="StateNamesString">"GeneratedStartStateForAbort1:INT:=1;
GeneratedFinalStateForAbort1:INT:=2;
EndState1:INT:=3;
ChoiceElement1:INT:=4;
EndState2:INT:=5;
ConstForceControl:INT:=6;
HoldOn:INT:=7;
StartState2:INT:=8;
DebugReady:INT:=9;
SystemExit:INT:=10;
DebugJog:INT:=11;
StartState3:INT:=12;
ConstForceReady:INT:=13;
Ready:INT:=14;
PowerOn:INT:=15;
StartState1:INT:=16;
"</v>
              <n n="StateNamesInitString" />
              <v n="ForceActionRemove">false</v>
              <d n="RegionsWithStartStatesTable" t="Hashtable" ckt="Guid" cvt="Int32">
                <v>cdd74fc6-ab6c-42b0-a0e3-dcfe71e7c4b0</v>
                <v>1</v>
                <v>4a44fd21-1cc4-4c6e-b212-e46c401f1062</v>
                <v>1</v>
                <v>00000000-0000-0000-0000-000000000000</v>
                <v>1</v>
              </d>
              <d n="RegionsWithHistoryStatesTable" t="Hashtable" ckt="Guid" cvt="Int32">
                <v>00000000-0000-0000-0000-000000000000</v>
                <v>1</v>
              </d>
              <d n="RegionsWithEndStatesTable" t="Hashtable" ckt="Guid" cvt="Int32">
                <v>cdd74fc6-ab6c-42b0-a0e3-dcfe71e7c4b0</v>
                <v>1</v>
                <v>4a44fd21-1cc4-4c6e-b212-e46c401f1062</v>
                <v>1</v>
              </d>
              <n n="BreakPointGuids" />
              <v n="UmlEditorRestrictions" t="EditorRestrictions">None</v>
              <v n="DUTObjectGuid">{d4cd907b-f780-4120-a858-f6494a60cc99}</v>
              <v n="DUTNamesObjectGuid">{195af0cb-f2db-4c3e-93e6-c69849560a7b}</v>
              <v n="TraceObject">{00000000-0000-0000-0000-000000000000}</v>
              <v n="IsCompiling">false</v>
              <v n="HideLanguageModel">false</v>
              <v n="DefaultStateSizeX">62</v>
              <v n="DefaultStateSizeY">32</v>
              <v n="SuppressAutomaticLibraryLoading">false</v>
              <v n="DiagramName">"SystemControl"</v>
              <v n="DiagramGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
              <v n="IsActionRemoving">false</v>
              <v n="ForceRepaintDiagram">false</v>
              <v n="Documentationdiagram">false</v>
              <v n="ApplicationGuidForDiagram">{00000000-0000-0000-0000-000000000000}</v>
              <v n="AutomaticLayOutHeightSpace">0</v>
              <v n="AutomaticLayOutWidthSpace">0</v>
              <d n="ElementObjects" t="Hashtable" ckt="Guid">
                <v>c47a1472-558c-46d4-ae71-43fedb982e7e</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"Ready_DO"</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"Ready_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"Ready"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">150</v>
                    <v n="LeftPosition">520</v>
                    <v n="WidthValue">149</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">63</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{c47a1472-558c-46d4-ae71-43fedb982e7e}</v>
                  <v n="ParentGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{174ab3d2-0e44-44df-8d59-db2398d1db6b}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">42U</v>
                </o>
                <v>798aa224-4f22-47b4-83f3-d463077d9ca0</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">"Exit_ENTRY"</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"Exit_ENTRY"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"Exit_DO"</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"Exit_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"SystemExit"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">140</v>
                    <v n="LeftPosition">970</v>
                    <v n="WidthValue">190</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">87</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{798aa224-4f22-47b4-83f3-d463077d9ca0}</v>
                  <v n="ParentGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{ef083823-547d-4634-a0ed-ce61f0ff88d2}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">55U</v>
                </o>
                <v>b0f179ea-d9c4-4ec6-8c54-23e29f9aa95e</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"Ready_DO"</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"Ready_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"ConstForceReady"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">360</v>
                    <v n="LeftPosition">878</v>
                    <v n="WidthValue">171</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">63</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{cdd74fc6-ab6c-42b0-a0e3-dcfe71e7c4b0}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{b0f179ea-d9c4-4ec6-8c54-23e29f9aa95e}</v>
                  <v n="ParentGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ContainerGuid">{c7b0cca1-bbda-43f6-9a20-ed041697c9e0}</v>
                  <v n="ShowedStereotype">{7617f6d1-6304-4ea5-a1e6-5aea901c227f}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">21U</v>
                </o>
                <v>d1de013b-485c-45ed-8181-0f2a6a83dea0</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">"PowerOn_ENTRY"</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"PowerOn_ENTRY"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"PowerOn_DO"</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"PowerOn_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"PowerOn"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">150</v>
                    <v n="LeftPosition">220</v>
                    <v n="WidthValue">231</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">87</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{d1de013b-485c-45ed-8181-0f2a6a83dea0}</v>
                  <v n="ParentGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{4f23cc48-0c2b-47c8-b9ec-5f6793471270}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">37U</v>
                </o>
                <v>10fb7d3e-11ec-4739-85a9-1036ab3abb01</v>
                <o t="UMLStateChartPseudoElement">
                  <o n="ElementVisualisation" t="UMLStateChartDiagramElementVisualisationDot">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">310</v>
                    <v n="LeftPosition">540</v>
                    <v n="WidthValue">20</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">20</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <v n="Condition">""</v>
                  <v n="HistoryType" t="HistoryTypes">None</v>
                  <v n="StateChartGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"ChoiceElement1"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartChoice</v>
                  <v n="_MaxDoCycleCalls" t="Int16">1</v>
                  <v n="DefaultCellSizeX">20</v>
                  <v n="DefaultCellSizeY">20</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{10fb7d3e-11ec-4739-85a9-1036ab3abb01}</v>
                  <v n="ParentGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{8299a968-bf0d-4147-9aca-374d06cc6f36}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                  <v n="ZOrder">44U</v>
                </o>
                <v>405bc795-3a09-4f7f-bdc0-ca230e609284</v>
                <o t="UMLStateChartPseudoElement">
                  <o n="ElementVisualisation" t="UMLStateChartDiagramElementVisualisationDot">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">2</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">403</v>
                    <v n="LeftPosition">190</v>
                    <v n="WidthValue">20</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">20</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <v n="Condition">""</v>
                  <v n="HistoryType" t="HistoryTypes">None</v>
                  <v n="StateChartGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"StartState2"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartStartState</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">20</v>
                  <v n="DefaultCellSizeY">20</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{4a44fd21-1cc4-4c6e-b212-e46c401f1062}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">2</v>
                  <v n="ElementObjectGuid">{405bc795-3a09-4f7f-bdc0-ca230e609284}</v>
                  <v n="ParentGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ContainerGuid">{2fc0ce94-9aeb-46fa-9c59-9fb7d7d4fc03}</v>
                  <v n="ShowedStereotype">{d6f218e6-a943-4ffe-8ca0-c56f26b4339d}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                  <v n="ZOrder">13U</v>
                </o>
                <v>293df4e2-b437-4724-9b9d-355be39136ea</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"HoldOn"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">150</v>
                    <v n="LeftPosition">30</v>
                    <v n="WidthValue">89</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">39</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{293df4e2-b437-4724-9b9d-355be39136ea}</v>
                  <v n="ParentGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{2305f203-73d2-4adb-97a2-75038656402d}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">39U</v>
                </o>
                <v>80e31146-0ea3-4c2e-8335-08a19f8972f8</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">"DebugJog_ENTRY"</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"DebugJog_ENTRY"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"DebugJog_DO"</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"DebugJog_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"DebugJog"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">520</v>
                    <v n="LeftPosition">180</v>
                    <v n="WidthValue">238</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">87</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{4a44fd21-1cc4-4c6e-b212-e46c401f1062}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{80e31146-0ea3-4c2e-8335-08a19f8972f8}</v>
                  <v n="ParentGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ContainerGuid">{2fc0ce94-9aeb-46fa-9c59-9fb7d7d4fc03}</v>
                  <v n="ShowedStereotype">{bcef3921-aac5-45e0-a040-1bd6484b737f}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">47U</v>
                </o>
                <v>23c8275e-3e5a-452a-9dac-57a65770120b</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">"ConstForceControl_ENTRY"</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"ConstForceControl_ENTRY"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"ConstForceControl_DO"</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"ConstForceControl_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"ConstForceControl"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">490</v>
                    <v n="LeftPosition">780</v>
                    <v n="WidthValue">301</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">87</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{cdd74fc6-ab6c-42b0-a0e3-dcfe71e7c4b0}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{23c8275e-3e5a-452a-9dac-57a65770120b}</v>
                  <v n="ParentGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ContainerGuid">{c7b0cca1-bbda-43f6-9a20-ed041697c9e0}</v>
                  <v n="ShowedStereotype">{858893a5-3c1e-4274-985f-ff7d922302c0}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">51U</v>
                </o>
                <v>2fc0ce94-9aeb-46fa-9c59-9fb7d7d4fc03</v>
                <o t="UMLStateChartComposite">
                  <v n="AllowCompositeActions">false</v>
                  <v n="ExecuteDoActionsWhenNestedCompositesAreActive">false</v>
                  <o n="ElementVisualisation" t="UMLCompositeVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">362</v>
                    <v n="LeftPosition">169</v>
                    <v n="WidthValue">307</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">252</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l n="Areas" t="ArrayList" cet="UMLArea">
                    <o>
                      <v n="Elementguid">{4a44fd21-1cc4-4c6e-b212-e46c401f1062}</v>
                      <v n="Name">"Region0"</v>
                      <v n="Position">0</v>
                      <v n="Priority">0</v>
                    </o>
                  </l>
                  <v n="StateChartGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"DebugMode"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartComposite</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">150</v>
                  <v n="DefaultCellSizeY">100</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{2fc0ce94-9aeb-46fa-9c59-9fb7d7d4fc03}</v>
                  <v n="ParentGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{4f130c1b-c5a4-421e-8958-3e52f5be6640}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-989556</v>
                  <v n="ZOrder">11U</v>
                </o>
                <v>1136ac63-da68-42e4-b826-14704770e40e</v>
                <o t="UMLStateChartPseudoElement">
                  <o n="ElementVisualisation" t="UMLStateChartDiagramElementVisualisationDot">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">2</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">530</v>
                    <v n="LeftPosition">1080</v>
                    <v n="WidthValue">20</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">20</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <v n="Condition">""</v>
                  <v n="HistoryType" t="HistoryTypes">None</v>
                  <v n="StateChartGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"EndState2"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartEndState</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">20</v>
                  <v n="DefaultCellSizeY">20</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{cdd74fc6-ab6c-42b0-a0e3-dcfe71e7c4b0}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">2</v>
                  <v n="ElementObjectGuid">{1136ac63-da68-42e4-b826-14704770e40e}</v>
                  <v n="ParentGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ContainerGuid">{c7b0cca1-bbda-43f6-9a20-ed041697c9e0}</v>
                  <v n="ShowedStereotype">{09d033d7-0bb8-4a1e-9ec4-6487779058c3}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                  <v n="ZOrder">52U</v>
                </o>
                <v>de408774-d66f-45d7-bf67-c39d4361d5e9</v>
                <o t="UMLStateChartPseudoElement">
                  <o n="ElementVisualisation" t="UMLStateChartDiagramElementVisualisationDot">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">40</v>
                    <v n="LeftPosition">60</v>
                    <v n="WidthValue">20</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">20</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <v n="Condition">""</v>
                  <v n="HistoryType" t="HistoryTypes">None</v>
                  <v n="StateChartGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"StartState1"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartStartState</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">20</v>
                  <v n="DefaultCellSizeY">20</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{de408774-d66f-45d7-bf67-c39d4361d5e9}</v>
                  <v n="ParentGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{9b8280a3-2b65-4680-88e0-843bb6accb48}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                  <v n="ZOrder">2U</v>
                </o>
                <v>00a7740d-a32f-49a1-b183-961c3efa6b04</v>
                <o t="UMLStateChartPseudoElement">
                  <o n="ElementVisualisation" t="UMLStateChartDiagramElementVisualisationDot">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">570</v>
                    <v n="LeftPosition">430</v>
                    <v n="WidthValue">20</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">20</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <v n="Condition">""</v>
                  <v n="HistoryType" t="HistoryTypes">None</v>
                  <v n="StateChartGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"EndState1"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartEndState</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">20</v>
                  <v n="DefaultCellSizeY">20</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{4a44fd21-1cc4-4c6e-b212-e46c401f1062}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{00a7740d-a32f-49a1-b183-961c3efa6b04}</v>
                  <v n="ParentGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ContainerGuid">{2fc0ce94-9aeb-46fa-9c59-9fb7d7d4fc03}</v>
                  <v n="ShowedStereotype">{3d9b4d8f-3043-46c4-bffd-b4015bb227cb}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                  <v n="ZOrder">48U</v>
                </o>
                <v>c7b0cca1-bbda-43f6-9a20-ed041697c9e0</v>
                <o t="UMLStateChartComposite">
                  <v n="AllowCompositeActions">false</v>
                  <v n="ExecuteDoActionsWhenNestedCompositesAreActive">false</v>
                  <o n="ElementVisualisation" t="UMLCompositeVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">340</v>
                    <v n="LeftPosition">750</v>
                    <v n="WidthValue">401</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">261</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l n="Areas" t="ArrayList" cet="UMLArea">
                    <o>
                      <v n="Elementguid">{cdd74fc6-ab6c-42b0-a0e3-dcfe71e7c4b0}</v>
                      <v n="Name">"Region0"</v>
                      <v n="Position">0</v>
                      <v n="Priority">0</v>
                    </o>
                  </l>
                  <v n="StateChartGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"ConstForceMode"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartComposite</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">150</v>
                  <v n="DefaultCellSizeY">100</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{c7b0cca1-bbda-43f6-9a20-ed041697c9e0}</v>
                  <v n="ParentGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{3fa3fbd4-4465-40ab-bea6-d3123625b84d}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-989556</v>
                  <v n="ZOrder">19U</v>
                </o>
                <v>a7bd6ea7-45da-451d-81d2-4910322f8ff0</v>
                <o t="UMLStateChartPseudoElement">
                  <o n="ElementVisualisation" t="UMLStateChartDiagramElementVisualisationDot">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">3</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">367</v>
                    <v n="LeftPosition">769</v>
                    <v n="WidthValue">20</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">20</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <v n="Condition">""</v>
                  <v n="HistoryType" t="HistoryTypes">None</v>
                  <v n="StateChartGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"StartState3"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartStartState</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">20</v>
                  <v n="DefaultCellSizeY">20</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{cdd74fc6-ab6c-42b0-a0e3-dcfe71e7c4b0}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">3</v>
                  <v n="ElementObjectGuid">{a7bd6ea7-45da-451d-81d2-4910322f8ff0}</v>
                  <v n="ParentGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ContainerGuid">{c7b0cca1-bbda-43f6-9a20-ed041697c9e0}</v>
                  <v n="ShowedStereotype">{494d60ef-9e74-4d33-a43d-1fb17f766f0b}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                  <v n="ZOrder">20U</v>
                </o>
                <v>6ce31cf1-ce0f-4603-b07a-3dcff0b5a4f7</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"Ready_DO"</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"Ready_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"DebugReady"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">400</v>
                    <v n="LeftPosition">250</v>
                    <v n="WidthValue">149</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">63</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{4a44fd21-1cc4-4c6e-b212-e46c401f1062}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{6ce31cf1-ce0f-4603-b07a-3dcff0b5a4f7}</v>
                  <v n="ParentGuid">{f26ced33-dea7-45dd-a280-164c04479403}</v>
                  <v n="ContainerGuid">{2fc0ce94-9aeb-46fa-9c59-9fb7d7d4fc03}</v>
                  <v n="ShowedStereotype">{1ecb2438-4f3d-4230-8988-7d1392ba64a9}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">14U</v>
                </o>
              </d>
              <v n="FirstPaint">true</v>
              <v n="NextElementID">0</v>
              <d n="UMLRelationObjects" t="Hashtable" ckt="Guid" cvt="UMLRelation">
                <v>9228576c-0bdc-4f1b-823b-ce632005a3c8</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{c47a1472-558c-46d4-ae71-43fedb982e7e}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">44U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <v n="ActionName">""</v>
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"system_control_param.is_system_control"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">20</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{10fb7d3e-11ec-4739-85a9-1036ab3abb01}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{9228576c-0bdc-4f1b-823b-ce632005a3c8}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>0</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>10</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">545</v>
                      <v n="AnchorTopPosition">208</v>
                      <v n="AnchorRelationID">{9228576c-0bdc-4f1b-823b-ce632005a3c8}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">545</v>
                      <v n="AnchorTopPosition">305</v>
                      <v n="AnchorRelationID">{9228576c-0bdc-4f1b-823b-ce632005a3c8}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{9228576c-0bdc-4f1b-823b-ce632005a3c8}</v>
                  <v n="RelationGuid">{9228576c-0bdc-4f1b-823b-ce632005a3c8}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">2</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>2</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>2195e458-bcc1-457c-a1d3-c666e96b47c3</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{405bc795-3a09-4f7f-bdc0-ca230e609284}</v>
                  <v n="HighlightedLine">true</v>
                  <v n="ZOrder">0U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">""</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">6</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{6ce31cf1-ce0f-4603-b07a-3dcff0b5a4f7}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{2195e458-bcc1-457c-a1d3-c666e96b47c3}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" />
                    <d n="flagsY" t="Hashtable" />
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">205</v>
                      <v n="AnchorTopPosition">408</v>
                      <v n="AnchorRelationID">{2195e458-bcc1-457c-a1d3-c666e96b47c3}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">245</v>
                      <v n="AnchorTopPosition">408</v>
                      <v n="AnchorRelationID">{2195e458-bcc1-457c-a1d3-c666e96b47c3}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{2195e458-bcc1-457c-a1d3-c666e96b47c3}</v>
                  <v n="RelationGuid">{2195e458-bcc1-457c-a1d3-c666e96b47c3}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">CompletionTransition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">true</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>3db8f560-4048-4686-80ae-3403b265fccc</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{b0f179ea-d9c4-4ec6-8c54-23e29f9aa95e}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">51U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"system_control_param.is_force_control"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">12</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{23c8275e-3e5a-452a-9dac-57a65770120b}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{3db8f560-4048-4686-80ae-3403b265fccc}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-160</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>20</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">985</v>
                      <v n="AnchorTopPosition">418</v>
                      <v n="AnchorRelationID">{3db8f560-4048-4686-80ae-3403b265fccc}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">985</v>
                      <v n="AnchorTopPosition">485</v>
                      <v n="AnchorRelationID">{3db8f560-4048-4686-80ae-3403b265fccc}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{3db8f560-4048-4686-80ae-3403b265fccc}</v>
                  <v n="RelationGuid">{3db8f560-4048-4686-80ae-3403b265fccc}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">2</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>2</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>da4107ca-c098-4bc4-a388-85922c56111d</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{23c8275e-3e5a-452a-9dac-57a65770120b}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">51U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"NOT system_control_param.is_force_control"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">13</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{b0f179ea-d9c4-4ec6-8c54-23e29f9aa95e}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{da4107ca-c098-4bc4-a388-85922c56111d}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-200</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-10</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">885</v>
                      <v n="AnchorTopPosition">485</v>
                      <v n="AnchorRelationID">{da4107ca-c098-4bc4-a388-85922c56111d}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">885</v>
                      <v n="AnchorTopPosition">418</v>
                      <v n="AnchorRelationID">{da4107ca-c098-4bc4-a388-85922c56111d}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{da4107ca-c098-4bc4-a388-85922c56111d}</v>
                  <v n="RelationGuid">{da4107ca-c098-4bc4-a388-85922c56111d}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>a8476197-6300-4c93-902e-c2fe9e563954</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{a7bd6ea7-45da-451d-81d2-4910322f8ff0}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">0U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">""</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">11</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{b0f179ea-d9c4-4ec6-8c54-23e29f9aa95e}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{a8476197-6300-4c93-902e-c2fe9e563954}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" />
                    <d n="flagsY" t="Hashtable" />
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">784</v>
                      <v n="AnchorTopPosition">377</v>
                      <v n="AnchorRelationID">{a8476197-6300-4c93-902e-c2fe9e563954}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">Right</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">873</v>
                      <v n="AnchorTopPosition">377</v>
                      <v n="AnchorRelationID">{a8476197-6300-4c93-902e-c2fe9e563954}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">Left</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{a8476197-6300-4c93-902e-c2fe9e563954}</v>
                  <v n="RelationGuid">{a8476197-6300-4c93-902e-c2fe9e563954}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">CompletionTransition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">true</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>79eabbe0-debd-4fbd-82cd-efefb312d7cb</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{10fb7d3e-11ec-4739-85a9-1036ab3abb01}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">44U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"system_control_param.system_control_mode=SystemControlMode.ConstForce"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">16</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{c7b0cca1-bbda-43f6-9a20-ed041697c9e0}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{79eabbe0-debd-4fbd-82cd-efefb312d7cb}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>300</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>0</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">555</v>
                      <v n="AnchorTopPosition">315</v>
                      <v n="AnchorRelationID">{79eabbe0-debd-4fbd-82cd-efefb312d7cb}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">791</v>
                      <v n="AnchorTopPosition">335</v>
                      <v n="AnchorRelationID">{79eabbe0-debd-4fbd-82cd-efefb312d7cb}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">Bottom</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">791</v>
                        <v n="AnchorTopPosition">315</v>
                        <v n="AnchorRelationID">{79eabbe0-debd-4fbd-82cd-efefb312d7cb}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{79eabbe0-debd-4fbd-82cd-efefb312d7cb}</v>
                  <v n="RelationGuid">{79eabbe0-debd-4fbd-82cd-efefb312d7cb}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">true</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>36661a36-d39e-4588-9d10-ae949c25e2e6</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{6ce31cf1-ce0f-4603-b07a-3dcff0b5a4f7}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">48U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"system_control_param.system_control_mode&lt;&gt;SystemControlMode.Debug or system_control_param.is_system_exit"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">17</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{00a7740d-a32f-49a1-b183-961c3efa6b04}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{36661a36-d39e-4588-9d10-ae949c25e2e6}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-90</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>220</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">394</v>
                      <v n="AnchorTopPosition">415</v>
                      <v n="AnchorRelationID">{36661a36-d39e-4588-9d10-ae949c25e2e6}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">435</v>
                      <v n="AnchorTopPosition">565</v>
                      <v n="AnchorRelationID">{36661a36-d39e-4588-9d10-ae949c25e2e6}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">435</v>
                        <v n="AnchorTopPosition">415</v>
                        <v n="AnchorRelationID">{36661a36-d39e-4588-9d10-ae949c25e2e6}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{36661a36-d39e-4588-9d10-ae949c25e2e6}</v>
                  <v n="RelationGuid">{36661a36-d39e-4588-9d10-ae949c25e2e6}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>e3e6ba2d-01f0-4867-a93e-cfe1584517c6</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{293df4e2-b437-4724-9b9d-355be39136ea}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">39U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"system_control_param.is_motor_poweron"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">2</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{d1de013b-485c-45ed-8181-0f2a6a83dea0}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{e3e6ba2d-01f0-4867-a93e-cfe1584517c6}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>70</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-30</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">114</v>
                      <v n="AnchorTopPosition">165</v>
                      <v n="AnchorRelationID">{e3e6ba2d-01f0-4867-a93e-cfe1584517c6}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">215</v>
                      <v n="AnchorTopPosition">165</v>
                      <v n="AnchorRelationID">{e3e6ba2d-01f0-4867-a93e-cfe1584517c6}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{e3e6ba2d-01f0-4867-a93e-cfe1584517c6}</v>
                  <v n="RelationGuid">{e3e6ba2d-01f0-4867-a93e-cfe1584517c6}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>07bd0535-440f-4d03-82ce-9a09f185003a</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{c47a1472-558c-46d4-ae71-43fedb982e7e}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">55U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"system_control_param.is_system_exit"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">3</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{798aa224-4f22-47b4-83f3-d463077d9ca0}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{07bd0535-440f-4d03-82ce-9a09f185003a}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" />
                    <d n="flagsY" t="Hashtable" />
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">664</v>
                      <v n="AnchorTopPosition">175</v>
                      <v n="AnchorRelationID">{07bd0535-440f-4d03-82ce-9a09f185003a}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">965</v>
                      <v n="AnchorTopPosition">175</v>
                      <v n="AnchorRelationID">{07bd0535-440f-4d03-82ce-9a09f185003a}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{07bd0535-440f-4d03-82ce-9a09f185003a}</v>
                  <v n="RelationGuid">{07bd0535-440f-4d03-82ce-9a09f185003a}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>f0e7e79f-0ecb-4a90-acbe-a4487510447f</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{d1de013b-485c-45ed-8181-0f2a6a83dea0}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">42U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"motor_state.is_motor_closedloop"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">19</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{c47a1472-558c-46d4-ae71-43fedb982e7e}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{f0e7e79f-0ecb-4a90-acbe-a4487510447f}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>40</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-20</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">446</v>
                      <v n="AnchorTopPosition">165</v>
                      <v n="AnchorRelationID">{f0e7e79f-0ecb-4a90-acbe-a4487510447f}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">515</v>
                      <v n="AnchorTopPosition">165</v>
                      <v n="AnchorRelationID">{f0e7e79f-0ecb-4a90-acbe-a4487510447f}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{f0e7e79f-0ecb-4a90-acbe-a4487510447f}</v>
                  <v n="RelationGuid">{f0e7e79f-0ecb-4a90-acbe-a4487510447f}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>54ffb393-7b59-4452-bb30-92ae2f9a8a45</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{b0f179ea-d9c4-4ec6-8c54-23e29f9aa95e}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">52U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"system_control_param.system_control_mode&lt;&gt;SystemControlMode.ConstForce or system_control_param.is_system_exit"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">23</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{1136ac63-da68-42e4-b826-14704770e40e}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{54ffb393-7b59-4452-bb30-92ae2f9a8a45}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-70</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>210</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">1044</v>
                      <v n="AnchorTopPosition">375</v>
                      <v n="AnchorRelationID">{54ffb393-7b59-4452-bb30-92ae2f9a8a45}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">1085</v>
                      <v n="AnchorTopPosition">525</v>
                      <v n="AnchorRelationID">{54ffb393-7b59-4452-bb30-92ae2f9a8a45}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">1085</v>
                        <v n="AnchorTopPosition">375</v>
                        <v n="AnchorRelationID">{54ffb393-7b59-4452-bb30-92ae2f9a8a45}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{54ffb393-7b59-4452-bb30-92ae2f9a8a45}</v>
                  <v n="RelationGuid">{54ffb393-7b59-4452-bb30-92ae2f9a8a45}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>f6bfd564-d64b-4a0c-b068-5dace3198248</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{de408774-d66f-45d7-bf67-c39d4361d5e9}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">39U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">""</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">1</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{293df4e2-b437-4724-9b9d-355be39136ea}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{f6bfd564-d64b-4a0c-b068-5dace3198248}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" />
                    <d n="flagsY" t="Hashtable" />
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">70</v>
                      <v n="AnchorTopPosition">55</v>
                      <v n="AnchorRelationID">{f6bfd564-d64b-4a0c-b068-5dace3198248}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">70</v>
                      <v n="AnchorTopPosition">145</v>
                      <v n="AnchorRelationID">{f6bfd564-d64b-4a0c-b068-5dace3198248}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{f6bfd564-d64b-4a0c-b068-5dace3198248}</v>
                  <v n="RelationGuid">{f6bfd564-d64b-4a0c-b068-5dace3198248}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">CompletionTransition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">true</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>45db100e-97a8-42dc-a95b-71bdaba77142</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{6ce31cf1-ce0f-4603-b07a-3dcff0b5a4f7}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">47U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"system_control_param.is_motor_jog"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">7</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{80e31146-0ea3-4c2e-8335-08a19f8972f8}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{45db100e-97a8-42dc-a95b-71bdaba77142}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-80</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>30</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">345</v>
                      <v n="AnchorTopPosition">458</v>
                      <v n="AnchorRelationID">{45db100e-97a8-42dc-a95b-71bdaba77142}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">345</v>
                      <v n="AnchorTopPosition">515</v>
                      <v n="AnchorRelationID">{45db100e-97a8-42dc-a95b-71bdaba77142}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{45db100e-97a8-42dc-a95b-71bdaba77142}</v>
                  <v n="RelationGuid">{45db100e-97a8-42dc-a95b-71bdaba77142}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">2</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>2</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>c8d9a4fc-ac07-49b4-a4b1-fb31f441a2c2</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{2fc0ce94-9aeb-46fa-9c59-9fb7d7d4fc03}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">42U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">""</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">21</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{c47a1472-558c-46d4-ae71-43fedb982e7e}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{c8d9a4fc-ac07-49b4-a4b1-fb31f441a2c2}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" />
                    <d n="flagsY" t="Hashtable" />
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">317</v>
                      <v n="AnchorTopPosition">357</v>
                      <v n="AnchorRelationID">{c8d9a4fc-ac07-49b4-a4b1-fb31f441a2c2}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">Top</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">3</v>
                      <v n="AnchorLeftPosition">525</v>
                      <v n="AnchorTopPosition">208</v>
                      <v n="AnchorRelationID">{c8d9a4fc-ac07-49b4-a4b1-fb31f441a2c2}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">3</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>2</v>
                      <o>
                        <v n="AnchorID">2</v>
                        <v n="AnchorLeftPosition">525</v>
                        <v n="AnchorTopPosition">275</v>
                        <v n="AnchorRelationID">{c8d9a4fc-ac07-49b4-a4b1-fb31f441a2c2}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">317</v>
                        <v n="AnchorTopPosition">275</v>
                        <v n="AnchorRelationID">{c8d9a4fc-ac07-49b4-a4b1-fb31f441a2c2}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{c8d9a4fc-ac07-49b4-a4b1-fb31f441a2c2}</v>
                  <v n="RelationGuid">{c8d9a4fc-ac07-49b4-a4b1-fb31f441a2c2}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">CompletionTransition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                    <v>Condition</v>
                    <v>DebugMode Completion</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>d972ec2e-9fce-4912-adfd-77f9a1dc4d09</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{80e31146-0ea3-4c2e-8335-08a19f8972f8}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">47U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"NOT system_control_param.is_motor_jog"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">8</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{6ce31cf1-ce0f-4603-b07a-3dcff0b5a4f7}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{d972ec2e-9fce-4912-adfd-77f9a1dc4d09}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-220</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>0</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">265</v>
                      <v n="AnchorTopPosition">515</v>
                      <v n="AnchorRelationID">{d972ec2e-9fce-4912-adfd-77f9a1dc4d09}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">265</v>
                      <v n="AnchorTopPosition">458</v>
                      <v n="AnchorRelationID">{d972ec2e-9fce-4912-adfd-77f9a1dc4d09}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{d972ec2e-9fce-4912-adfd-77f9a1dc4d09}</v>
                  <v n="RelationGuid">{d972ec2e-9fce-4912-adfd-77f9a1dc4d09}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>8371f4c7-1834-4d81-9856-ea37a0c0914f</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{10fb7d3e-11ec-4739-85a9-1036ab3abb01}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">44U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"system_control_param.system_control_mode=SystemControlMode.Debug"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">5</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{2fc0ce94-9aeb-46fa-9c59-9fb7d7d4fc03}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{8371f4c7-1834-4d81-9856-ea37a0c0914f}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-140</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>40</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">535</v>
                      <v n="AnchorTopPosition">315</v>
                      <v n="AnchorRelationID">{8371f4c7-1834-4d81-9856-ea37a0c0914f}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">395</v>
                      <v n="AnchorTopPosition">357</v>
                      <v n="AnchorRelationID">{8371f4c7-1834-4d81-9856-ea37a0c0914f}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">395</v>
                        <v n="AnchorTopPosition">315</v>
                        <v n="AnchorRelationID">{8371f4c7-1834-4d81-9856-ea37a0c0914f}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{8371f4c7-1834-4d81-9856-ea37a0c0914f}</v>
                  <v n="RelationGuid">{8371f4c7-1834-4d81-9856-ea37a0c0914f}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">2</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>2</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>f8b8adc4-a217-421b-adf6-f7d7a059b4e1</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{c7b0cca1-bbda-43f6-9a20-ed041697c9e0}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">42U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">""</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">22</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{c47a1472-558c-46d4-ae71-43fedb982e7e}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{f8b8adc4-a217-421b-adf6-f7d7a059b4e1}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" />
                    <d n="flagsY" t="Hashtable" />
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">895</v>
                      <v n="AnchorTopPosition">335</v>
                      <v n="AnchorRelationID">{f8b8adc4-a217-421b-adf6-f7d7a059b4e1}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">3</v>
                      <v n="AnchorLeftPosition">575</v>
                      <v n="AnchorTopPosition">208</v>
                      <v n="AnchorRelationID">{f8b8adc4-a217-421b-adf6-f7d7a059b4e1}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">3</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>2</v>
                      <o>
                        <v n="AnchorID">2</v>
                        <v n="AnchorLeftPosition">575</v>
                        <v n="AnchorTopPosition">275</v>
                        <v n="AnchorRelationID">{f8b8adc4-a217-421b-adf6-f7d7a059b4e1}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">895</v>
                        <v n="AnchorTopPosition">275</v>
                        <v n="AnchorRelationID">{f8b8adc4-a217-421b-adf6-f7d7a059b4e1}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{f8b8adc4-a217-421b-adf6-f7d7a059b4e1}</v>
                  <v n="RelationGuid">{f8b8adc4-a217-421b-adf6-f7d7a059b4e1}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">CompletionTransition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                    <v>Condition</v>
                    <v>ConstForceMode Completion</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
              </d>
              <v n="NextRelationID">0</v>
              <v n="DefaultAutomaticLayout">false</v>
              <o n="ClassDiagrammProperties" t="UMLDiagramProperties">
                <v n="ArrayOfPointerToClassPresentation" t="RelationTypes">Empty</v>
                <v n="ArrayOfClassPresentation" t="RelationTypes">Empty</v>
                <v n="ArrayOfInterfacePresentation" t="RelationTypes">Empty</v>
                <v n="ArrayOfInterfaceAggregationPresentation" t="RelationTypes">Empty</v>
                <v n="PointerToClassPresentation" t="RelationTypes">Empty</v>
                <v n="ClassPresentation" t="RelationTypes">Empty</v>
                <v n="InterfacePresentation" t="RelationTypes">Empty</v>
                <v n="InterfaceAggregationPresentation" t="RelationTypes">Empty</v>
                <v n="ShowRoleNames">true</v>
                <v n="ShowCardinalities">true</v>
                <v n="ShowRelationNames">true</v>
                <v n="ShowAttributesinClasses">false</v>
                <v n="ShowMethodsInClasses">false</v>
                <v n="ParametersMaximumLength">20</v>
              </o>
              <v n="IsFastStateDiagram">false</v>
              <l n="StereoTypeProfile" t="ArrayList" />
              <v n="RelationRoleID">23</v>
              <d n="PositionSerialization" t="Hashtable" ckt="Int64" cvt="Guid">
                <v>44</v>
                <v>54ffb393-7b59-4452-bb30-92ae2f9a8a45</v>
                <v>43</v>
                <v>f8b8adc4-a217-421b-adf6-f7d7a059b4e1</v>
                <v>42</v>
                <v>c8d9a4fc-ac07-49b4-a4b1-fb31f441a2c2</v>
                <v>41</v>
                <v>f0e7e79f-0ecb-4a90-acbe-a4487510447f</v>
                <v>40</v>
                <v>c47a1472-558c-46d4-ae71-43fedb982e7e</v>
                <v>39</v>
                <v>c47a1472-558c-46d4-ae71-43fedb982e7e</v>
                <v>38</v>
                <v>79eabbe0-debd-4fbd-82cd-efefb312d7cb</v>
                <v>37</v>
                <v>36661a36-d39e-4588-9d10-ae949c25e2e6</v>
                <v>35</v>
                <v>1136ac63-da68-42e4-b826-14704770e40e</v>
                <v>34</v>
                <v>da4107ca-c098-4bc4-a388-85922c56111d</v>
                <v>33</v>
                <v>3db8f560-4048-4686-80ae-3403b265fccc</v>
                <v>32</v>
                <v>23c8275e-3e5a-452a-9dac-57a65770120b</v>
                <v>31</v>
                <v>23c8275e-3e5a-452a-9dac-57a65770120b</v>
                <v>30</v>
                <v>a8476197-6300-4c93-902e-c2fe9e563954</v>
                <v>29</v>
                <v>b0f179ea-d9c4-4ec6-8c54-23e29f9aa95e</v>
                <v>28</v>
                <v>b0f179ea-d9c4-4ec6-8c54-23e29f9aa95e</v>
                <v>27</v>
                <v>a7bd6ea7-45da-451d-81d2-4910322f8ff0</v>
                <v>26</v>
                <v>c7b0cca1-bbda-43f6-9a20-ed041697c9e0</v>
                <v>23</v>
                <v>00a7740d-a32f-49a1-b183-961c3efa6b04</v>
                <v>22</v>
                <v>d972ec2e-9fce-4912-adfd-77f9a1dc4d09</v>
                <v>21</v>
                <v>45db100e-97a8-42dc-a95b-71bdaba77142</v>
                <v>20</v>
                <v>80e31146-0ea3-4c2e-8335-08a19f8972f8</v>
                <v>19</v>
                <v>80e31146-0ea3-4c2e-8335-08a19f8972f8</v>
                <v>18</v>
                <v>2195e458-bcc1-457c-a1d3-c666e96b47c3</v>
                <v>17</v>
                <v>6ce31cf1-ce0f-4603-b07a-3dcff0b5a4f7</v>
                <v>16</v>
                <v>6ce31cf1-ce0f-4603-b07a-3dcff0b5a4f7</v>
                <v>15</v>
                <v>405bc795-3a09-4f7f-bdc0-ca230e609284</v>
                <v>14</v>
                <v>8371f4c7-1834-4d81-9856-ea37a0c0914f</v>
                <v>13</v>
                <v>2fc0ce94-9aeb-46fa-9c59-9fb7d7d4fc03</v>
                <v>12</v>
                <v>9228576c-0bdc-4f1b-823b-ce632005a3c8</v>
                <v>11</v>
                <v>10fb7d3e-11ec-4739-85a9-1036ab3abb01</v>
                <v>10</v>
                <v>07bd0535-440f-4d03-82ce-9a09f185003a</v>
                <v>9</v>
                <v>798aa224-4f22-47b4-83f3-d463077d9ca0</v>
                <v>8</v>
                <v>798aa224-4f22-47b4-83f3-d463077d9ca0</v>
                <v>7</v>
                <v>e3e6ba2d-01f0-4867-a93e-cfe1584517c6</v>
                <v>6</v>
                <v>d1de013b-485c-45ed-8181-0f2a6a83dea0</v>
                <v>5</v>
                <v>d1de013b-485c-45ed-8181-0f2a6a83dea0</v>
                <v>4</v>
                <v>f6bfd564-d64b-4a0c-b068-5dace3198248</v>
                <v>3</v>
                <v>293df4e2-b437-4724-9b9d-355be39136ea</v>
                <v>2</v>
                <v>293df4e2-b437-4724-9b9d-355be39136ea</v>
                <v>1</v>
                <v>de408774-d66f-45d7-bf67-c39d4361d5e9</v>
              </d>
            </o>
          </Data>
          <TypeList>
            <Type n="ArrayList">System.Collections.ArrayList</Type>
            <Type n="ArrowTypes">{812dac4c-85cd-4336-bb2f-f967774b251e}</Type>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="Docked">{7586ffd4-4b2d-494c-aff5-a40d31dac111}</Type>
            <Type n="Double">System.Double</Type>
            <Type n="EditorRestrictions">{1ca7a370-7213-48b2-9df6-3ac7e85f0c68}</Type>
            <Type n="Guid">System.Guid</Type>
            <Type n="Hashtable">System.Collections.Hashtable</Type>
            <Type n="HistoryTypes">{3534dff0-3cd3-4ab6-8e74-b81ff8613005}</Type>
            <Type n="ImplicitStartStateTypes">{159536e2-c3a1-4501-a760-7b5009964f41}</Type>
            <Type n="Int16">System.Int16</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="RelationTypes">{f5146002-a332-47c0-9d9a-7997d539e6a9}</Type>
            <Type n="String">System.String</Type>
            <Type n="UInt32">System.UInt32</Type>
            <Type n="UMLAnchorPoint">{610ad96d-085d-4ced-95e0-831f42edefc2}</Type>
            <Type n="UMLArea">{7b0cf5f4-81b9-4f82-abc9-9de087e8469a}</Type>
            <Type n="UMLCompositeVisualisation">{408045ae-deed-4f23-8f67-f77d80b7a749}</Type>
            <Type n="UMLDiagramProperties">{71bc64fb-98e8-4f9a-b2ec-0da66cfaa0a0}</Type>
            <Type n="UMLRelation">{66eb2f12-934d-4c0a-8710-d6fec8d1ff48}</Type>
            <Type n="UMLRelationVisualisation">{79af0d10-00d2-4abe-9c91-6b4e07d4aa1d}</Type>
            <Type n="UMLStateChart">{9b0dd937-6691-44b8-b0c0-27601a5e098a}</Type>
            <Type n="UMLStateChartComposite">{05967c19-34ab-4e26-b363-c32e4509c5dc}</Type>
            <Type n="UMLStateChartDiagramElementVisualisationDot">{573ce27a-c0d4-453b-8ffd-6d125a13ad66}</Type>
            <Type n="UMLStateChartElement">{a9cbb7e7-7aa8-4772-a0f9-efee80bd48b2}</Type>
            <Type n="UMLStateChartElementVisualisation">{861a8beb-602e-4017-bf45-a602984c46fe}</Type>
            <Type n="UMLStateChartPseudoElement">{3569ebb7-c8a3-4ab4-b440-d179b9e0fe9b}</Type>
            <Type n="UMLType">{0197b136-405a-42ee-bb27-fd08b621d0cf}</Type>
          </TypeList>
        </XmlArchive>
      </StateChart>
    </Implementation>
    <Action Name="ConstForceControl_DO" Id="{5eebccd2-8522-43d7-816e-067ac0802640}">
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Action>
    <Action Name="ConstForceControl_ENTRY" Id="{8357e1b7-88f6-41cf-bfa0-7aeebec320b9}">
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Action>
    <Action Name="DebugJog_DO" Id="{8c36f437-5ca7-417b-b37b-159c749d264e}">
      <Implementation>
        <ST><![CDATA[target_velocity := system_control_param.jog_param.jog_velocity;]]></ST>
      </Implementation>
    </Action>
    <Action Name="DebugJog_ENTRY" Id="{535b0c77-eda4-474a-9745-c61a2f1cf3e4}">
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Action>
    <Action Name="Exit_DO" Id="{958c05c9-7223-4cd3-ae6c-85dda310b19b}">
      <Implementation>
        <ST><![CDATA[motorPower(
	Axis:= motor_axis, 
	Enable:= FALSE, 
	Enable_Positive:= TRUE, 
	Enable_Negative:= TRUE, 
	Override:= , 
	BufferMode:= , 
	Options:= , 
	Status=> , 
	Busy=> , 
	Active=> , 
	Error=> , 
	ErrorID=> );]]></ST>
      </Implementation>
    </Action>
    <Action Name="Exit_ENTRY" Id="{e0dc1617-e455-45fd-94e8-27be8ae21ef5}">
      <Implementation>
        <ST><![CDATA[target_velocity := 0;
]]></ST>
      </Implementation>
    </Action>
    <Action Name="PowerOn_DO" Id="{949cde52-772c-440d-8e0a-69f5e6463c55}">
      <Implementation>
        <ST><![CDATA[motorPower(
	Axis:= motor_axis, 
	Enable:= TRUE, 
	Enable_Positive:= TRUE, 
	Enable_Negative:= TRUE, 
	Override:= , 
	BufferMode:= , 
	Options:= , 
	Status=> , 
	Busy=> , 
	Active=> , 
	Error=> , 
	ErrorID=> );]]></ST>
      </Implementation>
    </Action>
    <Action Name="PowerOn_ENTRY" Id="{3acfe3ac-6e8d-41f2-8066-0b7dd094679c}">
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Action>
    <Action Name="Ready_DO" Id="{4707b248-c668-4be3-ae90-41598c95ecf2}">
      <Implementation>
        <ST><![CDATA[target_velocity := 0;]]></ST>
      </Implementation>
    </Action>
    <LineIds Name="SystemControl.ConstForceControl_DO">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="SystemControl.ConstForceControl_ENTRY">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="SystemControl.DebugJog_DO">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="SystemControl.DebugJog_ENTRY">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="SystemControl.Exit_DO">
      <LineId Id="3" Count="11" />
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="SystemControl.Exit_ENTRY">
      <LineId Id="2" Count="0" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="SystemControl.PowerOn_DO">
      <LineId Id="2" Count="11" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="SystemControl.PowerOn_ENTRY">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="SystemControl.Ready_DO">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>